### ISSUE TITLE
request: fit to a given size

### ISSUE THREAD

**Issue by vindarel** [vindarel/cl-str#57]
We have `(str:pad len s)`  (and pad-left, pad-right, pad-center) that fills s to a given length.

We have `(str:shorten len s)` that shortens it.

We don't have a function that either does the latter or the former and returns s of the given length.

cc @christophejunke, I see you have `fit-string` in your utility. 

How is this function named in other languages?

**Comment by christophejunke** [comment]
I don't really think this one already has a common name, I tried looking at rosettacode.org for various keywords but I didn't find anything.

The use-case for which the function was written was to print data in a table in a way that does not distort the resulting output;  that's why it was named `fit` originally, it seemed to be descriptive enough. An alternative could be `ensure-length` (?)
