### ISSUE TITLE
Wrong character name: NEXT-LINE. [LispWorks bug, fixed in master, didn't land in QL]

### ISSUE THREAD

**Issue by ijitai** [vindarel/cl-str#89]
```
; Loading "sento"
[package str]

**++++ Error between functions:
  Wrong character name: NEXT-LINE.
...
; *** 1 error detected, no fasl file produced.

Error: COMPILE-FILE-ERROR while compiling #<ASDF/LISP-ACTION:CL-SOURCE-FILE "str" "str">
```

Lispworks 8.01 M1 mbp

**Comment by vindarel** [comment]
This is a compatibility bug introduced lately. It is already fixed: https://github.com/vindarel/cl-str/pull/88 

but this bug was introduced in the latest Quicklisp release (February, 2023) :S To pick the fix, you have to use an earlier QL release, or to clone this library into your ~/quicklisp/local-projects.

Or, in fact, you can go to your current cl-str source (M-. in Slime) and edit its source. You need:

```lisp
(defvar *whitespaces* (list #\Backspace #\Tab #\Linefeed #\Newline #\Vt #\Page
                            #\Return #\Space #\Rubout
                            #+sbcl #\Next-Line #-sbcl (code-char 133) ;; <- changed
                            #\No-break_space)
```

I'll close when the next QL release is out.

**Comment by kilianmh** [comment]
You can load `cl-str` from _ultralisp_, where you always get the latest version.

Alternatively you can use [quick-patch](https://github.com/tdrhq/quick-patch) to grab `cl-str` including the bug fix:

```
(ql:quickload :quick-patch)
(quick-patch:register "https://github.com/vindarel/cl-str"
"cf2e7ae5e333b8a2dbfd01ec4ec26790b46eebf2")
(quick-patch:checkout-all "build/quick-patch/")
```

**Comment by kilianmh** [comment]
Now the next Quicklisp release is out which includes the patched version.
